name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      CI: "true"
    services:
      postgres:
        image: ankane/pgvector
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: helpme
          POSTGRES_PASSWORD: mysecretpassword
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Set up databases
        run: psql -d postgresql://helpme@localhost/postgres -f test_createdb.sql
        working-directory: infrastructure
        env:
          PGPASSWORD: mysecretpassword
      - name: Create extensions for chatbot database
        run:
          psql -d postgresql://helpme@localhost/chatbot_test -c "CREATE EXTENSION vector;" -c "CREATE EXTENSION \"uuid-ossp\";"
        env:
          PGPASSWORD: mysecretpassword
      - name: Create postgres.env from example
        run: cp packages/server/postgres.env.example packages/server/postgres.env
      - name: Create .env from .env.development
        run: cp packages/server/.env.development packages/server/.env
      - name: install node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: bahmutov/npm-install@v1
      - name: Run database migrations
        run: npm run migration:run
        working-directory: packages/server
        env:
          POSTGRES_USER: helpme
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
      - run: yarn test
